<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class FilterBookRequest extends FormRequest
{
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'minPage' => ['integer', 'min:0'],
            'maxPage' => ['integer', 'min:0'],
            'genres' => ['valid_genre_ids'],
            'published_date' => ['date', 'before:today'],
            'keyword' => ['string'],
            'author_id' => ['exists:author,id'],
        ];

    }

    /**
     * Messages generated by authorization errors.
     */
    public function messages(): array
    {
        return [
            'minPage.integer' => 'The number of pages must be an integer.',
            'minPage.min' => 'The number of pages must be zero or a positive number.',
            'maxPage.integer' => 'The number of pages must be an integer.',
            'maxPage.min' => 'The number of pages must be zero or a positive number.',
            'genres.valid_genre_ids' => 'You must select a valid genre.',
            'published_date.date' => 'The published date must be a valid date format.',
            'published_date.before' => 'The published date must be before today.',
            'keyword.string' => 'The keyword must be a valid string.',
            'author_id.exists' => 'You must select a valid author.',
        ];
    }

    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }
}
